### ISSUE TITLE
CCL/NAATI

### ISSUE THREAD

**Issue by binbingo** [uicestone/bingo-wp-theme#91]
- [x] **目前**：CCL考卷

 有FREE TRIAL标签的两个试卷，未注册用户仍会被引导到注册页面，注册成功后才能使用。

**需求:** CCL考卷有Free Trail 标签的，不需要注册就可以使用，且不会在“免费体验"-PTE练习中出现

<img width="1055" alt="ccl" src="https://user-images.githubusercontent.com/30458711/42132820-b6cf349e-7d62-11e8-850c-ad044c03f38d.PNG">

https://www.bingotraining.com/exam/naati_ccl%E8%80%83%E8%AF%95-%E5%8C%BB%E5%AD%A6%E7%AF%87_pregnancy/?finish=true

https://www.bingotraining.com/exam/naati_ccl%E8%80%83%E8%AF%95-%E6%95%99%E8%82%B2%E7%AF%87_behavioural-problem/?paper_id=14770

- [x] 结束考卷Bug, 修复为点击了“结束考卷”就自动结束全部考试并跳回”检查答案“|"删除答案”,“重新考试”页面。

- [x] 菜单项被遮挡BUG

例如：在这个页面https://www.bingotraining.com/exercise/repeat-sentence-%E7%BB%83%E4%B9%A01/，让录音音波出现后， 然后选择菜单-免费体验-听力阅读链接，就可以看到部分菜单被录音音波遮挡住了。

3Q

**Comment by uicestone** [comment]
我放弃了使用统一Free Trial标签的尝试。免费试用的CCL请使用Free Trial CCL标签，然后进入的链接为 `https://www.bingotraining.com/exercise/?tag=free-trial-ccl`

**Comment by binbingo** [comment]
试了下考卷
https://www.bingotraining.com/exam/naati_ccl%E8%80%83%E8%AF%95-%E5%8C%BB%E5%AD%A6%E7%AF%87_pregnancy/?finish=true 
添加CCL Free Trial, 仍然需要注册才可免费试用。目前考卷是不是无法在添加标签后做到无登陆状态下的免费使用。

**Comment by uicestone** [comment]
考卷确实不支持，因为需要保存进度，必须要有账号。 @binbingo

**Comment by binbingo** [comment]
好的

Uice Lu <notifications@github.com>于2018年7月11日 周三下午9:11写道：
